// Code generated by "stringer -type=AccountType"; DO NOT EDIT.

package stage1

import "strconv"

const _AccountType_name = "AssetsLiabilitiesEquityRevenuesExpenses"

var _AccountType_index = [...]uint8{0, 6, 17, 23, 31, 39}

func (i AccountType) String() string {
	if i < 0 || i >= AccountType(len(_AccountType_index)-1) {
		return "AccountType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccountType_name[_AccountType_index[i]:_AccountType_index[i+1]]
}
