// Code generated by "binpack -name ledgerText ledger.html"; DO NOT EDIT.

package webui

const ledgerText = "{{define \"head\" -}}\n<style>\n</style>\n{{end}}\n{{- define \"body\" -}}\n<h1>Ledger for {{.Account}}</h1>\n{{if not .Account -}}\n<p>Missing account query!</p>\n{{else -}}\n<table>\n  <thead>\n    <tr>\n      <th>Ref</th>\n      <th>Date</th>\n      <th>Description</th>\n      <th>Debit</th>\n      <th>Credit</th>\n      <th>Balance</th>\n    </tr>\n  </thead>\n  <tbody>\n    {{- range .Entries}}\n    <tr>\n      <td>{{.Position}}</td>\n      <td>{{.Date}}</td>\n      <td>{{.Description}}</td>\n      {{- if eq .Amount.Number 0}}\n      <td></td>\n      <td></td>\n      {{else if gt .Amount.Number 0}}\n      <td>{{.Amount}}</td>\n      <td></td>\n      {{else}}\n      <td></td>\n      <td>{{.Amount}}</td>\n      {{- end}}\n      <td>{{.Balance}}</td>\n      <tr>\n    {{- end}}\n  </tbody>\n</table>\n{{end}}\n{{- end}}\n"
