// Code generated by "binpack -name reconcileText reconcile.html"; DO NOT EDIT.

package webui

const reconcileText = "{{define \"head\" -}}\n<style>\n</style>\n{{end}}\n{{- define \"body\" -}}\n<table>\n  <thead>\n    <tr>\n      <th>Location</th>\n      <th>Date</th>\n      <th>Description</th>\n      <th>Amount</th>\n      <th>Balance</th>\n    </tr>\n  </thead>\n  <tbody>\n    {{- range .Entries}}\n    <tr>\n      <td>{{.Position}}</td>\n      <td>{{.Date}}</td>\n      <td>{{.Description}}</td>\n      <td>{{.Amount}}</td>\n      <td>{{.Balance}}</td>\n      <tr>\n    {{- end}}\n  </tbody>\n</table>\n{{end}}\n"
