// Code generated by "binpack -name styleText style.css"; DO NOT EDIT.

package webui

const styleText = "nav.sitenav {\n    display: flex;\n    align-items: center;\n}\nnav.sitenav a {\n    text-decoration: none;\n    color: inherit;\n}\nnav.sitenav h1 {\n    margin: 0;\n}\nnav.sitenav ul {\n    display: flex;\n    padding-left: 10px;\n    margin: 0;\n}\nnav.sitenav ul > li {\n    padding-left: 10px;\n    padding-right: 10px;\n    list-style-type: none;\n}\n\ntable, th, td {\n    border: 1px solid black;\n    border-collapse: collapse;\n}\nth, td {\n    padding-left: 5px;\n    padding-right: 5px;\n}\nth {\n    text-align: left;\n}\n\ntr.section {\n    border-top: 2px solid black;\n}\ntd.amount {\n    text-align: right;\n}\n"
