// Code generated by "binpack -name trialText trial.html"; DO NOT EDIT.

package webui

const trialText = "{{- define \"body\" -}}\n<h1>Trial Balance</h1>\n<table>\n  <thead>\n    <tr>\n      <th>Account</th>\n      <th>Debit Bal</th>\n      <th>Credit Bal</th>\n    </tr>\n  </thead>\n  <tbody>\n    {{- range .Rows}}\n    <tr{{if .Account}} class=\"section\"{{end}}>\n      <td>{{.Account}}</td>\n\n      <td class=\"amount\">{{if .DebitBal.Unit.Symbol}}{{.DebitBal}}{{end}}</td>\n      <td class=\"amount\">{{if .CreditBal.Unit.Symbol}}{{.CreditBal}}{{end}}</td>\n      <tr>\n    {{- end}}\n  </tbody>\n</table>\n{{- end}}\n"
